//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPTController.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PPTController.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        public static string Bluetooth {
            get {
                return ResourceManager.GetString("Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default HotSpot IP :.
        /// </summary>
        public static string DefaultHotSpotIP {
            get {
                return ResourceManager.GetString("DefaultHotSpotIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected Computer.
        /// </summary>
        public static string DetectedComputer {
            get {
                return ResourceManager.GetString("DetectedComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Flick Mode.
        /// </summary>
        public static string FlickMode {
            get {
                return ResourceManager.GetString("FlickMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Screen.
        /// </summary>
        public static string FullScreen {
            get {
                return ResourceManager.GetString("FullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HotSpot.
        /// </summary>
        public static string HotSpot {
            get {
                return ResourceManager.GetString("HotSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to use?.
        /// </summary>
        public static string HowToUse {
            get {
                return ResourceManager.GetString("HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address (Sample {192.168.0.10}).
        /// </summary>
        public static string IPAddressSample {
            get {
                return ResourceManager.GetString("IPAddressSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal View.
        /// </summary>
        public static string NormalView {
            get {
                return ResourceManager.GetString("NormalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paired Device.
        /// </summary>
        public static string PairedDevice {
            get {
                return ResourceManager.GetString("PairedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPT Controller Setup.
        /// </summary>
        public static string PPTControllerSetup {
            get {
                return ResourceManager.GetString("PPTControllerSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start PPT.
        /// </summary>
        public static string StartPPT {
            get {
                return ResourceManager.GetString("StartPPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPT Controller.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Touch Mode.
        /// </summary>
        public static string TouchMode {
            get {
                return ResourceManager.GetString("TouchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate by each action.
        /// </summary>
        public static string VibrateControl {
            get {
                return ResourceManager.GetString("VibrateControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit us.
        /// </summary>
        public static string VisitUs {
            get {
                return ResourceManager.GetString("VisitUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vote us.
        /// </summary>
        public static string VoteUs {
            get {
                return ResourceManager.GetString("VoteUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wifi.
        /// </summary>
        public static string Wifi {
            get {
                return ResourceManager.GetString("Wifi", resourceCulture);
            }
        }
    }
}
